// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _123Pay.Models;

namespace _123Pay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220205232250_InitializeModel")]
    partial class InitializeModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "fdbde63e-6a08-4f35-a1ac-fca72f698f59",
                            ConcurrencyStamp = "6adf74c5-2bef-4a19-a2d5-7140ece44009",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "71fac99f-2553-48da-8bca-4954274053bc",
                            RoleId = "fdbde63e-6a08-4f35-a1ac-fca72f698f59"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("_123Pay.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "71fac99f-2553-48da-8bca-4954274053bc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b39499a0-0101-45a9-8578-66e6ffe9d86f",
                            Email = "alfredoiv.magpantay@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALFREDOIV.MAGPANTAY@YAHOO.COM",
                            NormalizedUserName = "ADMINISTRATOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEKHaJFeliWYa9aO0g3YxUToQuXMh3cDwpGm90SxXCEuRNora+tC/9cSR0mSwX1Cc6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f202683f-bf4a-419b-bf4e-5a1d6c3efc4c",
                            TwoFactorEnabled = false,
                            UserName = "administrator"
                        });
                });

            modelBuilder.Entity("_123Pay.Models.PaymentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("AttachmentFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merchant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessorId");

                    b.ToTable("PaymentRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountName = "Customer 1",
                            AccountNo = "8011223301",
                            Amount = 100.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 534, DateTimeKind.Local).AddTicks(7645),
                            CustomerName = "Wan Talamera",
                            Merchant = "AT&T",
                            OtherDetails = "Other Details 1",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100001",
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = 2,
                            AccountName = "Customer 2",
                            AccountNo = "8011223302",
                            Amount = 200.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6756),
                            CustomerName = "Wan Talamera",
                            Merchant = "Netflix",
                            OtherDetails = "Other Details 2",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100002",
                            Status = "PROCESSING"
                        },
                        new
                        {
                            Id = 3,
                            AccountName = "Customer 3",
                            AccountNo = "8011223303",
                            Amount = 300.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6892),
                            CustomerName = "Wan Talamera",
                            Merchant = "Amazon",
                            OtherDetails = "Other Details 3",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100003",
                            Status = "FAILED"
                        },
                        new
                        {
                            Id = 4,
                            AccountName = "Customer 4",
                            AccountNo = "8011223304",
                            Amount = 400.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6896),
                            CustomerName = "Wan Talamera",
                            Merchant = "EBay",
                            OtherDetails = "Other Details 4",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100004",
                            Status = "DONE"
                        },
                        new
                        {
                            Id = 5,
                            AccountName = "Customer 5",
                            AccountNo = "8011223305",
                            Amount = 500.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6898),
                            CustomerName = "Wan Talamera",
                            Merchant = "TELEPAY",
                            OtherDetails = "Other Details 5",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100005",
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = 6,
                            AccountName = "Customer 6",
                            AccountNo = "8011223306",
                            Amount = 600.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6902),
                            CustomerName = "Wan Talamera",
                            Merchant = "AT&T",
                            OtherDetails = "Other Details 6",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100006",
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = 7,
                            AccountName = "Customer 7",
                            AccountNo = "8011223307",
                            Amount = 700.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6904),
                            CustomerName = "Wan Talamera",
                            Merchant = "Netflix",
                            OtherDetails = "Other Details 7",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100007",
                            Status = "PROCESSING"
                        },
                        new
                        {
                            Id = 8,
                            AccountName = "Customer 8",
                            AccountNo = "8011223308",
                            Amount = 800.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6906),
                            CustomerName = "Wan Talamera",
                            Merchant = "Amazon",
                            OtherDetails = "Other Details 8",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100008",
                            Status = "FAILED"
                        },
                        new
                        {
                            Id = 9,
                            AccountName = "Customer 9",
                            AccountNo = "8011223309",
                            Amount = 900.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6908),
                            CustomerName = "Wan Talamera",
                            Merchant = "EBay",
                            OtherDetails = "Other Details 9",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100009",
                            Status = "DONE"
                        },
                        new
                        {
                            Id = 10,
                            AccountName = "Customer 10",
                            AccountNo = "8011223310",
                            Amount = 1000.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6910),
                            CustomerName = "Wan Talamera",
                            Merchant = "TELEPAY",
                            OtherDetails = "Other Details 10",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100010",
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = 11,
                            AccountName = "Customer 11",
                            AccountNo = "8011223311",
                            Amount = 1100.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6912),
                            CustomerName = "Wan Talamera",
                            Merchant = "AT&T",
                            OtherDetails = "Other Details 11",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100011",
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = 12,
                            AccountName = "Customer 12",
                            AccountNo = "8011223312",
                            Amount = 1200.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6914),
                            CustomerName = "Wan Talamera",
                            Merchant = "Netflix",
                            OtherDetails = "Other Details 12",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100012",
                            Status = "PROCESSING"
                        },
                        new
                        {
                            Id = 13,
                            AccountName = "Customer 13",
                            AccountNo = "8011223313",
                            Amount = 1300.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6916),
                            CustomerName = "Wan Talamera",
                            Merchant = "Amazon",
                            OtherDetails = "Other Details 13",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100013",
                            Status = "FAILED"
                        },
                        new
                        {
                            Id = 14,
                            AccountName = "Customer 14",
                            AccountNo = "8011223314",
                            Amount = 1400.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6917),
                            CustomerName = "Wan Talamera",
                            Merchant = "EBay",
                            OtherDetails = "Other Details 14",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100014",
                            Status = "DONE"
                        },
                        new
                        {
                            Id = 15,
                            AccountName = "Customer 15",
                            AccountNo = "8011223315",
                            Amount = 1500.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6919),
                            CustomerName = "Wan Talamera",
                            Merchant = "TELEPAY",
                            OtherDetails = "Other Details 15",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100015",
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = 16,
                            AccountName = "Customer 16",
                            AccountNo = "8011223316",
                            Amount = 1600.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6921),
                            CustomerName = "Wan Talamera",
                            Merchant = "AT&T",
                            OtherDetails = "Other Details 16",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100016",
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = 17,
                            AccountName = "Customer 17",
                            AccountNo = "8011223317",
                            Amount = 1700.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6924),
                            CustomerName = "Wan Talamera",
                            Merchant = "Netflix",
                            OtherDetails = "Other Details 17",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100017",
                            Status = "PROCESSING"
                        },
                        new
                        {
                            Id = 18,
                            AccountName = "Customer 18",
                            AccountNo = "8011223318",
                            Amount = 1800.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6927),
                            CustomerName = "Wan Talamera",
                            Merchant = "Amazon",
                            OtherDetails = "Other Details 18",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100018",
                            Status = "FAILED"
                        },
                        new
                        {
                            Id = 19,
                            AccountName = "Customer 19",
                            AccountNo = "8011223319",
                            Amount = 1900.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6929),
                            CustomerName = "Wan Talamera",
                            Merchant = "EBay",
                            OtherDetails = "Other Details 19",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100019",
                            Status = "DONE"
                        },
                        new
                        {
                            Id = 20,
                            AccountName = "Customer 20",
                            AccountNo = "8011223320",
                            Amount = 2000.0,
                            ClientName = "ABC Pay",
                            CreateDate = new DateTime(2022, 2, 6, 7, 22, 49, 536, DateTimeKind.Local).AddTicks(6931),
                            CustomerName = "Wan Talamera",
                            Merchant = "TELEPAY",
                            OtherDetails = "Other Details 20",
                            ProcessorId = "71fac99f-2553-48da-8bca-4954274053bc",
                            ReferenceNo = "PR2022020100020",
                            Status = "PENDING"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("_123Pay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("_123Pay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_123Pay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("_123Pay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_123Pay.Models.PaymentRequest", b =>
                {
                    b.HasOne("_123Pay.Models.ApplicationUser", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId");

                    b.Navigation("Processor");
                });
#pragma warning restore 612, 618
        }
    }
}
